import { Navbar } from '../components/Navbar';
import { BottomNavbar } from '../components/BottomNavbar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { Toaster } from "@/components/ui/toaster";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-background font-sans antialiased">
        <div className="flex min-h-screen flex-col">
          <Navbar />
          <main className="flex-1 pb-16 md:pb-0"> {/* Add padding-bottom for bottom navbar */}
            {children}
          </main>
          <BottomNavbar />
          <Toaster />
        </div>
      </body>
    </html>
  )
}
